---
- name: Install fish
  block:
    - name: Add fish 3 PPA
      apt_repository:
        repo: ppa:fish-shell/release-3

    - name: Install fish
      apt:
        name: fish
        state: present

    - name: Set fish as default shell
      user:
        name: "{{ ansible_env.USER }}"
        shell: /usr/bin/fish
  become: true
