- name: Install fish
  block:
    - name: Add fish 3 PPA
      apt_repository:
        repo: ppa:fish-shell/release-3

    - name: Install fish
      apt:
        name: fish
        state: present
  become: yes
