- name: Install neovim
  block:
    - name: Check if neovim exists
      stat:
        path: /opt/neovim/nvim.appimage
      register: neovim

    - name: Fresh install, move, chmod of neovim
      block:
      - name: Download nightly neovim
        get_url:
          url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
          dest: /tmp/nvim.appimage
        register: download_out

      - name: Create neovim directory
        file:
          path: /opt/neovim/
          state: directory

      - name: Move neovim to opt
        copy:
          src: /tmp/nvim.appimage
          dest: /opt/neovim/nvim.appimage

      - name: Make neovim executable
        file:
          path: /opt/neovim/nvim.appimage
          mode: '0755'

      - name: Symlink neovim
        file:
          src: /opt/neovim/nvim.appimage
          dest: /usr/local/bin/nvim
          state: link
      when: not neovim.stat.exists
  become: yes

- name: Install vim-plug
  block:
    - name: Check if vim-plug exists
      stat:
        path: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/autoload/plug.vim"
      register: vim_plug

    - name: Install vim-plug (for neovim)
      shell:
        cmd: |
          sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
          https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
      when: not vim_plug.stat.exists

- name: Install neovim plugins
  block:
    - name: Check if neovim plugins are already installed
      stat:
        path: "{{ lookup('env', 'HOME') }}/.config/nvim/plugged"
      register: neovim_plugged
    - name: Initial neovim plugins installation
      shell:
        cmd: nvim --headless +PlugInstall +qa
      when: not neovim_plugged.stat.exists
