- name: Install fd
  block:
    - name: Install fd-find
      package:
        name: fd-find
        state: present

    - name: Symlink fd-find (fdfind) to fd
      file:
        src: "{{ lookup('pipe', 'which fdfind') }}"
        dest: /usr/local/bin/fd
        state: link
  become: yes
