---
- name: Install fnm
  block:
    - name: Check if fnm exists
      stat:
        path: "{{ lookup('env', 'HOME') }}/.fnm"
      register: fnm

    - name: Install fnm
      block:
        - name: Download fnm installer script
          get_url:
            url: https://fnm.vercel.app/install
            dest: /tmp/fnm-install.sh

        - name: Execute fnm installer script
          shell:
            cmd: cat /tmp/fnm-install.sh | bash
      when: not fnm.stat.exists
