- name: Install fnm
  block:
    - name: Check if fnm exists
      stat:
        path: "{{ lookup('env', 'HOME') }}/.fnm"
      register: fnm

    - name: Install fnm
      shell:
        cmd: |
          curl -fsSL https://fnm.vercel.app/install | bash
      when: not fnm.stat.exists
