---
- name: Install lazygit
  block:
    - name: Check if lazygit exists
      stat:
        path: /usr/local/bin/lazygit
      register: lazygit

    - name: Fresh install, unzip, move, chmod of lazygit
      block:
        - name: Download lazygit v0.28.2
          get_url:
            url: https://github.com/jesseduffield/lazygit/releases/download/v0.28.2/lazygit_0.28.2_Linux_x86_64.tar.gz
            dest: /tmp/lazygit

        - name: Unarchive lazygit
          unarchive:
            src: /tmp/lazygit
            dest: /tmp

        - name: Install lazygit
          copy:
            src: /tmp/lazygit
            dest: /usr/local/bin/lazygit
            mode: '+x'
      when: not lazygit.stat.exists
  become: true

- name: Install delta
  block:
    - name: Check if delta exists
      stat:
        path: /usr/local/bin/delta
      register: delta

    - name: Fresh install, unzip, move, chmod of delta
      block:
        - name: Download delta v0.8.0
          get_url:
            url: https://github.com/dandavison/delta/releases/download/0.8.0/delta-0.8.0-x86_64-unknown-linux-gnu.tar.gz
            dest: /tmp/delta-0.8.0-x86_64-unknown-linux-gnu.tar.gz

        - name: Unarchive delta
          unarchive:
            src: /tmp/delta-0.8.0-x86_64-unknown-linux-gnu.tar.gz
            dest: /tmp

        - name: Install delta
          copy:
            src: /tmp/delta-0.8.0-x86_64-unknown-linux-gnu/delta
            dest: /usr/local/bin/delta
            mode: '+x'
      when: not delta.stat.exists
  become: true
