---
- name: Install lazygit
  block:
    - name: Check if lazygit exists
      stat:
        path: /usr/local/bin/lazygit
      register: lazygit

    - name: Fresh install, unzip, move, chmod of lazygit
      block:
        - name: Download lazygit v0.28.2
          get_url:
            url: https://github.com/jesseduffield/lazygit/releases/download/v0.28.2/lazygit_0.28.2_Linux_x86_64.tar.gz
            dest: /tmp/lazygit

        - name: Unarchive lazygit
          unarchive:
            src: /tmp/lazygit
            dest: /tmp

        - name: Install lazygit
          copy:
            src: /tmp/lazygit
            dest: /usr/local/bin/lazygit
            mode: '+x'
      when: not lazygit.stat.exists
  become: true
