---
- name: Install vscode
  block:
    - name: Check if vscode exists
      stat:
        path: /usr/bin/code
      register: vscode

    - name: Setup for vscode installation
      block:
        - name: Add vscode GPG apt key
          apt_key:
            url: https://packages.microsoft.com/keys/microsoft.asc
            state: present
          become: true

        - name: Add vscode repository
          apt_repository:
            repo: deb https://packages.microsoft.com/repos/code stable main
            state: present
            update_cache: true
          become: true

        - name: Install vscode
          apt:
            name:
              - apt-transport-https
              - code
            state: latest
            update_cache: true
          become: true

        - name: Install vscode plugins
          command: "code --install-extension {{ item }}"
          loop: "{{ vscode_plugins }}"
      when: not vscode.stat.exists
