---
- name: Install docker
  block:
    - name: Check if docker exists
      stat:
        path: /usr/bin/docker
      register: docker

    - name: Setup for docker installation
      block:
        - name: Install required system packages for docker
          apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
            state: present

        - name: Add Docker GPG apt Key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            keyring: /usr/share/keyrings/docker-archive-keyring.gpg
            state: present

        - name: Add Docker Repository
          apt_repository:
            repo: >
              deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
              https://download.docker.com/linux/ubuntu
              {{ ansible_distribution_release }} stable
            state: present
            update_cache: true

        - name: Install docker-ce
          apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
            state: latest
            update_cache: true

        - name: Add docker group
          group:
            name: docker
            state: present

        - name: "Add \"{{ ansible_env.USER }}\" to the docker group"
          shell:
            cmd: "usermod -aG docker {{ ansible_env.USER }}"
      become: true
      when: not docker.stat.exists

- name: Install docker-compose
  block:
    - name: Check if docker-compose exists
      stat:
        path: /usr/local/bin/docker-compose
      register: docker_compose

    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '+x'
      become: true
      when: not docker_compose.stat.exists
