---
- name: Install neovim
  block:
    - name: Check if neovim exists
      stat:
        path: /opt/neovim/nvim.appimage
      register: neovim

    - name: Fresh install, move, chmod of neovim
      block:
        - name: Create neovim directory
          file:
            path: /opt/neovim/
            state: directory

        - name: Download nightly neovim
          get_url:
            url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
            dest: /opt/neovim/nvim.appimage
            mode: '+x'

        - name: Symlink neovim
          file:
            src: /opt/neovim/nvim.appimage
            dest: /usr/local/bin/nvim
            state: link
      when: not neovim.stat.exists
  become: true

- name: Install vim-plug
  block:
    - name: Check if vim-plug exists
      stat:
        path: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"
      register: vim_plug

    - name: Download and move vim-plug
      block:
        - name: Create vim-plug directory
          file:
            path: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload"
            state: directory

        - name: Download vim-plug
          get_url:
            url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
            dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"
      when: not vim_plug.stat.exists

- name: Install neovim plugins
  block:
    - name: Check if neovim plugins are already installed
      stat:
        path: "{{ ansible_env.HOME }}/.config/nvim/plugged"
      register: neovim_plugged

    - name: Initial neovim plugins installation
      command: nvim --headless +PlugInstall +qa
      when: not neovim_plugged.stat.exists

- name: Install vscode
  block:
    - name: Check if vscode exists
      stat:
        path: /usr/bin/code
      register: vscode

    - name: Setup for vscode installation
      block:
        - name: Add vscode GPG apt key
          apt_key:
            url: https://packages.microsoft.com/keys/microsoft.asc
            state: present
          become: true

        - name: Add vscode repository
          apt_repository:
            repo: deb https://packages.microsoft.com/repos/code stable main
            state: present
            update_cache: true
          become: true

        - name: Install vscode
          apt:
            name:
              - apt-transport-https
              - code
            state: latest
            update_cache: true
          become: true

        - name: Install vscode plugins
          command: "code --install-extension {{ item }}"
          loop: "{{ vscode_plugins }}"
      when: not vscode.stat.exists
