---
- name: Install lazygit
  block:
    - name: Check if lazygit exists
      stat:
        path: /usr/local/bin/lazygit
      register: lazygit

    - name: Fresh install, unzip, move, chmod of lazygit
      block:
        - name: Create lazygit directory
          file:
            path: /tmp/lazygit
            state: directory

        - name: Download lazygit v0.31.4
          get_url:
            url: https://github.com/jesseduffield/lazygit/releases/download/v0.31.4/lazygit_0.31.4_Linux_x86_64.tar.gz
            dest: /tmp/lazygit/lazygit.tar.gz

        - name: Unarchive lazygit
          unarchive:
            src: /tmp/lazygit/lazygit.tar.gz
            dest: /tmp/lazygit

        - name: Install lazygit
          copy:
            src: /tmp/lazygit/lazygit
            dest: /usr/local/bin/lazygit
            mode: '+x'
          become: true
      when: not lazygit.stat.exists

- name: Install delta
  block:
    - name: Check if delta exists
      stat:
        path: /usr/local/bin/delta
      register: delta

    - name: Fresh install, unzip, move, chmod of delta
      block:
        - name: Create delta directory
          file:
            path: /tmp/delta
            state: directory

        - name: Download delta v0.10.2
          get_url:
            url: https://github.com/dandavison/delta/releases/download/0.10.2/delta-0.10.2-x86_64-unknown-linux-gnu.tar.gz
            dest: /tmp/delta/delta.tar.gz

        - name: Unarchive delta
          unarchive:
            src: /tmp/delta/delta.tar.gz
            dest: /tmp/delta

        - name: Install delta
          copy:
            src: /tmp/delta/delta-0.10.2-x86_64-unknown-linux-gnu/delta
            dest: /usr/local/bin/delta
            mode: '+x'
          become: true
      when: not delta.stat.exists
