---
- name: Import docker tasks
  import_tasks: docker.yml

- name: Import editor tasks
  import_tasks: editor.yml

- name: Import git tasks
  import_tasks: git.yml

- name: Import node tasks
  import_tasks: node.yml

- name: Import packages tasks
  import_tasks: packages.yml

- name: Import symlinks tasks
  import_tasks: symlinks.yml

- name: Import terminal tasks
  import_tasks: terminal.yml
