---
- name: Install node (via fnm)
  block:
    - name: Check if fnm exists
      stat:
        path: "{{ ansible_env.HOME }}/.fnm"
      register: fnm

    - name: Install fnm
      block:
        - name: Download fnm installer script
          get_url:
            url: https://fnm.vercel.app/install
            dest: /tmp/fnm-install.sh

        - name: Execute fnm installer script
          shell:
            cmd: cat /tmp/fnm-install.sh | bash

        - name: Install node v16 with fnm
          shell:
            cmd: |
              eval "$(fnm env)"
              fnm use 16 --install-if-missing
              fnm default $(node --version)
          environment:
            PATH: "{{ ansible_env.HOME }}/.fnm:{{ ansible_env.PATH }}"
      when: not fnm.stat.exists

- name: Install npm packages
  block:
    - name: Check if npm packages exists
      shell: which {{ item }}
      register: npm_packages_register
      changed_when: false
      ignore_errors: true
      loop: "{{ npm_packages_installs }}"

    - name: Install npm packages
      shell:
        cmd: |
          eval "$(fnm env)"
          npm install {{ item.item }} -g
      environment:
        PATH: "{{ ansible_env.HOME }}/.fnm:{{ ansible_env.PATH }}"
      loop: "{{ npm_packages_register.results }}"
      loop_control:
        label: "{{ item.item }}"
      when: item.failed
