---
- name: Install basic packages
  apt:
    name: "{{ packages_installs }}"
    state: present
  become: true

- name: Install fd
  block:
    - name: Check if fd exists
      stat:
        path: /usr/local/bin/fd
      register: fd

    - name: Install and symlink fd-find
      block:
        - name: Install fd-find
          apt:
            name: fd-find
            state: present

        - name: Symlink fd-find (fdfind) to fd
          file:
            src: "{{ lookup('pipe', 'which fdfind') }}"
            dest: /usr/local/bin/fd
            state: link
      become: true
      when: not fd.stat.exists

- name: Install zoxide
  block:
    - name: Check if zoxide exists
      stat:
        path: /usr/local/bin/zoxide
      register: zoxide

    - name: Fresh install, unzip, move, chmod of zoxide
      block:
        - name: Download zoxide v0.7.0
          get_url:
            url: https://github.com/ajeetdsouza/zoxide/releases/download/v0.7.0/zoxide-x86_64-unknown-linux-musl.tar.gz
            dest: /tmp/zoxide-x86_64-unknown-linux-musl.tar.gz

        - name: Unzip zoxide
          unarchive:
            src: /tmp/zoxide-x86_64-unknown-linux-musl.tar.gz
            dest: /tmp

        - name: Install zoxide
          copy:
            src: /tmp/zoxide-x86_64-unknown-linux-musl/zoxide
            dest: /usr/local/bin/zoxide
            mode: '+x'
      when: not zoxide.stat.exists
  become: true
