gui:
  border: 'single'
  expandFocusedSidePanel: true
  returnImmediately: true

customCommands:
  containers:
    - name: bash
      attach: true
      command: 'docker exec -it {{ .Container.ID }} bash'
    - name: postgres
      attach: true
      command: 'docker exec -it {{ .Container.ID }} sh -c "psql -U postgres"'
