---
packages_installs:
  - bash
  - bat
  - build-essential
  - curl
  - fonts-firacode
  - fzf
  - git
  - jq
  - moreutils
  - ripgrep
  - shellcheck
  - silversearcher-ag
  - tldr
  - tmux
  - tree
  - wget
  - xclip
  - zsh

dotfiles_symlinks:
  - .config/Code/User/keybindings.json
  - .config/Code/User/settings.json
  - .config/fish/config.fish
  - .config/gitconfig
  - .config/kitty/kitty.conf
  - .config/lazygit/config.yml
  - .config/nvim
  - .config/starship.toml
  - .gitconfig
  - .tmux.conf
  - .zshrc

scripts_symlinks:
  - {src: command-cache.sh, command: command-cache}
  - {src: connect-to-bighost-dev.sh, command: bighost-dev}
  - {src: gitlab-search-and-clone.sh, command: qsc}

vscode_plugins:
  - aaron-bond.better-comments
  - bmewburn.vscode-intelephense-client
  - coenraads.disableligatures
  - liximomo.sftp
  - pkief.material-icon-theme
  - vscodevim.vim
  - yzhang.markdown-all-in-one

npm_packages_installs:
  - npm-check
