---
packages_installs:
  - bash
  - build-essential
  - curl
  - fonts-firacode
  - fzf
  - git
  - jq
  - moreutils
  - ripgrep
  - shellcheck
  - silversearcher-ag
  - tldr
  - tmux
  - tree
  - wget
  - xclip
  - zsh

dotfiles_symlinks:
  - .config/Code/User/keybindings.json
  - .config/Code/User/settings.json
  - .config/fish/config.fish
  - .config/git
  - .config/kitty/kitty.conf
  - .config/lazygit/config.yml
  - .config/nvim
  - .config/starship.toml
  - .tmux.conf
  - .zshrc

scripts_symlinks:
  - {src: command-cache.sh, command: command-cache}
  - {src: tmux-jump.sh, command: tmux-jump}

npm_packages_installs:
  - {name: '@fsouza/prettierd', command: prettierd}
  - {name: eslint_d, command: eslint_d}
  - {name: npm-check, command: npm-check}
