add_newline = false

[directory]
truncation_length = 0

[username]
show_always = true

[aws]
# only show if im logged in or not (other info is not really useful)
symbol = '☁️'
format = '[$symbol]($style)'
