- name: Install all basic packages, which do not need extra setup
  import_tasks: packages_basic.yml

- name: Install all special packages, which need extra setup
  import_tasks: packages_special.yml

- name: Symlink basic files in dotfiles repo
  import_tasks: symlinks.yml

- name: Install neovim specific things
  import_tasks: neovim.yml