- name: Install packages | Special - fd
  become: yes
  block:
    - name: Install fd-find
      package:
        name: fd-find
        state: present
    - name: Symlink fd-find (fdfind) to fd
      file:
        src: "{{ lookup('pipe', 'which fdfind') }}"
        dest: /usr/local/bin/fd
        state: link

- name: Install packages | Special - fnm
  block:
    - name: Check if fnm exists
      stat:
        path: "{{ lookup('env', 'HOME') }}/.fnm"
      register: fnm
    - name: Install fnm if not already installed
      raw: curl -fsSL https://fnm.vercel.app/install | bash
      when: not fnm.stat.exists

- name: Install packages | Special - lazygit
  become: yes
  block:
    - name: Add [DEPRECATED] lazygit PPA
      apt_repository:
        repo: ppa:lazygit-team/release
    - name: Install lazygit
      package:
        name: lazygit
        state: present

- name: Install packages | Special - zoxide
  become: yes
  block:
    - name: Check if zoxide exists
      stat:
        path: /opt/zoxide/zoxide
      register: zoxide
    - name: Fresh install, unzip, move, chmod of zoxide
      block:
      - name: Download zoxide v0.7.0
        get_url:
          url: https://github.com/ajeetdsouza/zoxide/releases/download/v0.7.0/zoxide-x86_64-unknown-linux-musl.tar.gz
          dest: /tmp/zoxide-x86_64-unknown-linux-musl.tar.gz
      - name: Unzip zoxide
        unarchive:
          src: /tmp/zoxide-x86_64-unknown-linux-musl.tar.gz
          dest: /tmp
      - name: Move zoxide to opt
        copy:
          src: /tmp/zoxide-x86_64-unknown-linux-musl/
          dest: /opt/zoxide
      - name: Make zoxide executable
        file:
          path: /opt/zoxide/zoxide
          mode: '0755'
      when: not zoxide.stat.exists
