- name: Install packages | Special - fd
  block:
  - name: Install fd-find
    become: yes
    package:
      name: fd-find
      state: present
  - name: Symlink fd-find (fdfind) to fd
    become: yes
    file:
      src: "{{ lookup('pipe', 'which fdfind') }}"
      dest: /usr/local/bin/fd
      state: link

- name: Install packages | Special - fnm
  block:
    - name: Check if fnm exists
      stat:
        path: "{{ lookup('env', 'HOME') }}/.fnm"
      register: fnm
    - name: Install fnm if not already installed
      raw: curl -fsSL https://fnm.vercel.app/install | bash
      when: not fnm.stat.exists

- name: Install packages | Special - lazygit
  block:
    - name: Add [DEPRECATED] lazygit PPA
      become: yes
      apt_repository:
        repo: ppa:lazygit-team/release
    - name: Install lazygit
      become: yes
      package:
        name: lazygit
        state: present
