- name: Setup local environment
  hosts: localhost
  roles:
    - role: terminal
    - role: shell
    - role: symlinks
    - role: packages
    - role: neovim

  vars:
    packages_install:
      - bash
      - bat
      - build-essential
      - curl
      - fzf
      - gcc
      - git
      - jq
      - ripgrep
      - shellcheck
      - silversearcher-ag
      - tldr
      - wget
      - xclip

    dotfiles_symlink:
      - .config/Code/User/keybindings.json
      - .config/Code/User/settings.json
      - .config/fish/config.fish
      - .config/kitty/kitty.conf
      - .config/lazygit/config.yml
      - .config/nvim
      - .config/starship.toml

    scripts_symlink:
      - { src: connect-to-bighost-dev.sh, command: bighost-dev }
      - { src: gitlab-search-and-clone.sh, command: qc }
