---
- name: Install kitty terminal
  block:
    - name: Check if kitty terminal exists
      stat:
        path: "{{ ansible_env.HOME }}/.local/kitty.app"
      register: kitty

    - name: Install kitty terminal
      block:
        - name: Download kitty terminal install script
          get_url:
            url: https://sw.kovidgoyal.net/kitty/installer.sh
            dest: /tmp/kitty-install.sh

        - name: Execute kitty terminal install script
          shell:
            cmd: cat /tmp/kitty-install.sh | sh /dev/stdin launch=n

        - name: Setup kitty desktop file
          block:
            - name: Link kitty
              file:
                src: "{{ ansible_env.HOME }}/.local/kitty.app/bin/kitty"
                dest: /usr/local/bin/kitty
                state: link
              become: true

            - name: Create share directories
              file:
                path: "{{ ansible_env.HOME }}/.local/share/applications"
                state: directory

            - name: Copy kitty.desktop
              copy:
                src: "{{ ansible_env.HOME }}/.local/kitty.app/share/applications/kitty.desktop"
                dest: "{{ ansible_env.HOME }}/.local/share/applications/"

            - name: Update kitty.desktop icon
              shell:
                cmd: >
                  sed -i
                  "s|Icon=kitty|Icon={{ ansible_env.HOME }}/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png|g"
                  {{ ansible_env.HOME }}/.local/share/applications/kitty.desktop
      when: not kitty.stat.exists

- name: Install starship
  block:
    - name: Check if starship exists
      stat:
        path: /usr/local/bin/starship
      register: starship

    - name: Install starship
      block:
        - name: Download starship install script
          get_url:
            url: https://starship.rs/install.sh
            dest: /tmp/starship-install.sh

        - name: Execute starship install script
          shell:
            cmd: cat /tmp/starship-install.sh | sh /dev/stdin -y
      when: not starship.stat.exists
