hotKeys:
  switch-to-secrets:
    shortCut: Shift-S
    overrides: true
    description: Switch to secrets from current context
    command: "secrets $NAMESPACE"
  switch-to-pods:
    shortCut: Shift-P
    overrides: true
    description: Switch to pods from current context
    command: "pods $NAMESPACE"
