plugins:
  stream-pretty-json-logs:
    shortCut: Ctrl-L
    description: Pretty json logs
    confirm: false
    scopes:
      - pod
    command: sh
    background: false
    args:
      - -c
      - |
        set -eu
        kubectl -n "$NAMESPACE" logs "$NAME" \
          -f --tail=100 \
          --context  $CONTEXT \
          | jq -CSR '. as $line | try (fromjson) catch $line'

  vim-logs-pods:
    shortCut: Ctrl-V
    description: Open in vim
    scopes:
      - pods
    command: sh
    background: false
    args:
      - -c
      - |
        set -eu
        kubectl -n "$NAMESPACE" logs "$NAME" \
          --all-containers=true \
          --prefix=true \
          --timestamps=true \
          | ${EDITOR:-vim} - \
            -c 'setlocal nomodified'

  vim-logs-containers:
    shortCut: Ctrl-V
    description: Open in vim
    scopes:
      - containers
    command: sh
    background: false
    args:
      - -c
      - |
        set -eu
        kubectl -n "$NAMESPACE" logs "$POD" -c "$NAME" \
          --timestamps=true \
          | ${EDITOR:-vim} - \
            -c 'setlocal nomodified'
