plugins:
  stream-pretty-json-logs:
    shortCut: Ctrl-L
    description: Pretty json logs
    confirm: false
    scopes:
    - pod
    command: sh
    background: false
    args:
    - -c
    - "kubectl logs $NAME -f --tail=100 -n $NAMESPACE --context  $CONTEXT | jq -CSR '. as $line | try (fromjson) catch $line'"
