-- options should be first to have leader set (some plugins otherwise do not get the correct leader key)
require("eckon.core.options")
require("eckon.core.keymaps")
require("eckon.core.autocmds")
require("eckon.core.commands")
